#!/usr/bin/env python3
"""Перечисление типов доменных событий."""
from enum import Enum

class EventType(Enum):
    HOSTNAME_CHANGED = "HOSTNAME_CHANGED"
    VENDOR_CHANGED = "VENDOR_CHANGED"
    DEVICE_IDENTITY_CHANGED = "DEVICE_IDENTITY_CHANGED"
    CAPABILITY_ADDED = "CAPABILITY_ADDED"
    CAPABILITY_REMOVED = "CAPABILITY_REMOVED"
    SESSION_STARTED = "SESSION_STARTED"
    SESSION_ENDED = "SESSION_ENDED"
    PRESENCE_APPEARED = "PRESENCE_APPEARED"
    PRESENCE_DISAPPEARED = "PRESENCE_DISAPPEARED"
    SUMMARY_CHANGED = "SUMMARY_CHANGED"
