#!/usr/bin/env python3
"""Константы и версии для Presence Engine."""

# Версии (Замечание №13)
ENGINE_VERSION = "1.0.0"
RULES_VERSION = "1.0.0"
FEATURE_VERSION = "1.0.0"
PROVIDER_VERSION = "1.0.0"

# Пороги для правил
NEW_DEVICE_HISTORY_DAYS = 7
RETURNING_DEVICE_MIN_VISITS = 2
REGULAR_VISITOR_MIN_VISITS = 10
DAILY_VISITOR_MIN_DAYS = 5
WEEKEND_VISITOR_RATIO = 0.6
NIGHT_VISITOR_RATIO = 0.4
BUSINESS_HOURS_RATIO = 0.7

BUSINESS_HOURS_START = 9
BUSINESS_HOURS_END = 18
NIGHT_HOURS_START = 22
NIGHT_HOURS_END = 6
